name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly, 1.87.0]  # stable, beta, nightly, and MSRV
        mode: ["", "--release"]
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: cache rust toolchain
        uses: Swatinem/rust-cache@v2

      - name: cargo test
        run: cargo test ${{ matrix.mode }}

  deny:
    name: cargo deny
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: cargo deny
        uses: EmbarkStudios/cargo-deny-action@v2

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: cargo fmt
        run: cargo fmt --all -- --check

  doc:
    name: cargo doc
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: cargo doc
        run: cargo doc --no-deps

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: cargo clippy
        run: cargo clippy --bins -- -D warnings

  artifact:
    name: build musl target
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: cache rust toolchain
        uses: Swatinem/rust-cache@v2

      - name: install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: cargo build
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: beacon-linux-x86_64
          path: target/x86_64-unknown-linux-musl/release/beacon
